# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171012_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
    ]
