# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(),
        ),
    ]
